<?php

namespace Blogger\BlogBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatest($limit, $offset, $userID)
    {
        $queryBuilder = $this->createQueryBuilder('book');
        $userID = null;

        if ($userID != null)
        {
            $queryBuilder
                ->where('book.submittedBy = ' . $userID)
                ->orderBy('book.id', 'DESC')
                ->setFirstResult($offset)
                ->setMaxResults($limit);
        }
        else {
            $queryBuilder
                -> orderBy('book.id', 'DESC')
                ->setFirstResult($offset)
                ->setMaxResults($limit);
        }


        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }

    public function getPage($booksPerPage, $currentPage = 1, $userID) {
        $offset = ($currentPage - 1) * $booksPerPage;
        return $this->getLatest($booksPerPage, $offset, $userID);

    }

    public function countBooks() {

        $queryBuilder = $this->createQueryBuilder('book');
        $queryBuilder->select('COUNT(book)');
        $count = $queryBuilder->getQuery()->getSingleScalarResult();
        return $count;

    }

    public function getSearchResults($string) {
        $dql = $this->createQueryBuilder('book')
            ->where('book.title LIKE :term')
            ->orWhere('book.bookAuthor LIKE :term')
            ->orWhere('book.description LIKE :term')
            ->setParameter('term', '%' . $string . '%');
        $query = $dql->getQuery();
        return $query->getResult();
    }
}
