#blogger_blog_homepage:
#    path:     /
#    defaults: { _controller: BloggerBlogBundle:Page:index }
blogger_author:
    path:     /my_posts/
    defaults: { _controller: BloggerBlogBundle:Page:author }

blogger_stranger:
    path:     /users/{id}
    defaults: { _controller: BloggerBlogBundle:Page:stranger, id: 1 }
    requirements:
          id: \d+

index:
    path:     /{page}
    defaults: { _controller: BloggerBlogBundle:Page:pagination, page:1 }
    requirements:
        page: \d+

blogger_post_view:
    path:     /view/{id}
    defaults: { _controller: BloggerBlogBundle:Post:view }
    requirements:
      id: \d+

blogger_post_create:
    path:     /create/{bookId}
    defaults: { _controller: BloggerBlogBundle:Post:create }
    requirements:
      bookId: \d+

blogger_post_edit:
    path:     /edit/{id}
    defaults: { _controller: BloggerBlogBundle:Post:edit }
    requirements:
      id: \d+

blogger_post_delete:
    path:     /delete/{id}
    defaults: { _controller: BloggerBlogBundle:Post:delete }
    requirements:
      id: \d+

user_login:
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login }

user_logout:
    path:     /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

blogger_book_view:
    path:     /book_view/{id}
    defaults: { _controller: BloggerBlogBundle:Book:view }
    requirements:
          id: \d+

blogger_book_create:
    path:     /book_create/
    defaults: { _controller: BloggerBlogBundle:Book:create }

blogger_book_edit:
    path:     /book_edit/{id}
    defaults: { _controller: BloggerBlogBundle:Book:edit }
    requirements:
          id: \d+

blogger_book_delete:
    path:     /book_delete/{id}
    defaults: { _controller: BloggerBlogBundle:Book:delete }
    requirements:
          id: \d+

admin_user_view:
    path:     admin_view
    defaults: { _controller: BloggerBlogBundle:Admin:view }

admin_user_edit:
    path:     admin_edit
    defaults: { _controller: BloggerBlogBundle:Admin:edit }
    requirements:
          id: \d+

admin_user_delete:
    path:     admin_delete
    defaults: { _controller: BloggerBlogBundle:Admin:delete }
    requirements:
              id: \d+

book_search:
  path: /search
  defaults: { _controller: BloggerBlogBundle:Page:search }

search_handling:
  path: /search_handling
  defaults: { _controller: BloggerBlogBundle:Page:handleSearch }

rs_joindin_events_all:
    path: /events
    defaults: { _controller: BloggerBlogBundle:Joindin:events }

rs_joindin_event:
    path: /events/{index}
    defaults: { _controller: BloggerBlogBundle:Joindin:event }
    requirements:
      index: \d+

rs_joindin_event_talks:
    path: /events/{index}/talks/
    defaults: { _controller: BloggerBlogBundle:Joindin:talks }
    requirements:
      index: \d+

blogger_api_search:
    path: /books/api/search
    defaults: { _controller: BloggerBlogBundle:Book:apiSearch }

blogger_api_searchHandle:
    path: /searchHandleApi
    defaults: { _controller: BloggerBlogBundle:Book:handleSearch }

blogger_api_book_result:
    path: /singleBook/{id}
    defaults: { _controller: BloggerBlogBundle:Book:apiBook }
    requirements:

blogger_api_NYT_book_list:
    path: /best-sellers
    defaults: { _controller: BloggerBlogBundle:Book:bestSeller }
    requirements:
