blogger_blog_homepage:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Page:index }

blogger_author:
    path:     /my_posts
    defaults: { _controller: BloggerBlogBundle:Page:author }

index:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Page:index }

blogger_post_view:
    path:     /view/{id}
    defaults: { _controller: BloggerBlogBundle:Post:view }
    requirements:
      id: \d+

blogger_post_create:
    path:     /create/{bookId}
    defaults: { _controller: BloggerBlogBundle:Post:create }
    requirements:
      bookId: \d+

blogger_post_edit:
    path:     /edit/{id}
    defaults: { _controller: BloggerBlogBundle:Post:edit }
    requirements:
      id: \d+

blogger_post_delete:
    path:     /delete/{id}
    defaults: { _controller: BloggerBlogBundle:Post:delete }
    requirements:
      id: \d+

user_login:
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login }

user_logout:
    path:     /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

blogger_book_view:
    path:     /book_view/{id}
    defaults: { _controller: BloggerBlogBundle:Book:view }
    requirements:
          id: \d+

blogger_book_create:
    path:     /book_create/
    defaults: { _controller: BloggerBlogBundle:Book:create }

blogger_book_edit:
    path:     /book_edit/{id}
    defaults: { _controller: BloggerBlogBundle:Book:edit }
    requirements:
          id: \d+

blogger_book_delete:
    path:     /book_delete/{id}
    defaults: { _controller: BloggerBlogBundle:Book:delete }
    requirements:
          id: \d+
