user_homepage:
    path:     /UserIndex
    defaults: { _controller: UserBundle:Default:index }

user_login:
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login }

user_logout:
    path:     /logout
    defaults: { _controller: FOSUserBundle:Security:logout }
